/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppBar: typeof import('./components/app/bar/AppBar.vue')['default']
    AppDrawer: typeof import('./components/app/drawer/AppDrawer.vue')['default']
    AppDrawerFooter: typeof import('./components/app/drawer/AppDrawerFooter.vue')['default']
    AppDrawerMenu: typeof import('./components/app/drawer/AppDrawerMenu.vue')['default']
    AppDrawerMenuAccount: typeof import('./components/app/drawer/AppDrawerMenuAccount.vue')['default']
    AppDrawerMenuHistory: typeof import('./components/app/drawer/AppDrawerMenuHistory.vue')['default']
    AppDrawerMenuImport: typeof import('./components/app/drawer/AppDrawerMenuImport.vue')['default']
    AppDrawerMenuLogout: typeof import('./components/app/drawer/AppDrawerMenuLogout.vue')['default']
    AppDrawerMenuMedia: typeof import('./components/app/drawer/AppDrawerMenuMedia.vue')['default']
    AppDrawerMenuServer: typeof import('./components/app/drawer/AppDrawerMenuServer.vue')['default']
    AppFooter: typeof import('./components/AppFooter.vue')['default']
    BuildCommit: typeof import('./components/BuildCommit.vue')['default']
    BuildVersion: typeof import('./components/BuildVersion.vue')['default']
    DialogConfirm: typeof import('./components/dialogs/DialogConfirm.vue')['default']
    DialogConfirmEdit: typeof import('./components/dialogs/DialogConfirmEdit.vue')['default']
    Discord: typeof import('./components/icons/discord.vue')['default']
    FormUserChangePassword: typeof import('./components/forms/user/FormUserChangePassword.vue')['default']
    FormUserEdit: typeof import('./components/forms/user/FormUserEdit.vue')['default']
    HelloWorld: typeof import('./components/HelloWorld.vue')['default']
    LocaleSelector: typeof import('./components/LocaleSelector.vue')['default']
    LoginForm: typeof import('./components/LoginForm.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    ThemeSelector: typeof import('./components/ThemeSelector.vue')['default']
  }
}
