/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppBar: typeof import('./components/app/Bar.vue')['default']
    AppDrawer: typeof import('./components/app/drawer/Drawer.vue')['default']
    AppDrawerFooter: typeof import('./components/app/drawer/Footer.vue')['default']
    AppDrawerMenu: typeof import('./components/app/drawer/menu/Menu.vue')['default']
    AppDrawerMenuAccount: typeof import('./components/app/drawer/menu/Account.vue')['default']
    AppDrawerMenuHistory: typeof import('./components/app/drawer/menu/History.vue')['default']
    AppDrawerMenuImport: typeof import('./components/app/drawer/menu/Import.vue')['default']
    AppDrawerMenuLogout: typeof import('./components/app/drawer/menu/Logout.vue')['default']
    AppDrawerMenuMedia: typeof import('./components/app/drawer/menu/Media.vue')['default']
    AppDrawerMenuServer: typeof import('./components/app/drawer/menu/Server.vue')['default']
    AppFooter: typeof import('./components/AppFooter.vue')['default']
    BuildCommit: typeof import('./components/BuildCommit.vue')['default']
    BuildVersion: typeof import('./components/BuildVersion.vue')['default']
    DialogConfirm: typeof import('./components/dialog/Confirm.vue')['default']
    DialogConfirmEdit: typeof import('./components/dialog/ConfirmEdit.vue')['default']
    FormUserChangePassword: typeof import('./components/form/user/ChangePassword.vue')['default']
    FormUserEdit: typeof import('./components/form/user/Edit.vue')['default']
    HelloWorld: typeof import('./components/HelloWorld.vue')['default']
    LocaleSelector: typeof import('./components/LocaleSelector.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    ThemeSelector: typeof import('./components/ThemeSelector.vue')['default']
  }
}
