/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AnnouncementCard: typeof import('./components/announcement/Card.vue')['default']
    AppFooter: typeof import('./components/AppFooter.vue')['default']
    DialogConfirm: typeof import('./components/dialog/Confirm.vue')['default']
    DialogConfirmEdit: typeof import('./components/dialog/ConfirmEdit.vue')['default']
    FragmentBuildCommit: typeof import('./fragments/fragment/BuildCommit.vue')['default']
    FragmentBuildVersion: typeof import('./fragments/fragment/BuildVersion.vue')['default']
    FragmentDialogConfirm: typeof import('./fragments/fragment/dialog/Confirm.vue')['default']
    FragmentDialogConfirmEdit: typeof import('./fragments/fragment/dialog/ConfirmEdit.vue')['default']
    FragmentLocaleSelector: typeof import('./fragments/fragment/LocaleSelector.vue')['default']
    FragmentSnackQueue: typeof import('./fragments/fragment/SnackQueue.vue')['default']
    FragmentThemeSelector: typeof import('./fragments/fragment/ThemeSelector.vue')['default']
    HelloWorld: typeof import('./components/HelloWorld.vue')['default']
    LayoutAppBar: typeof import('./fragments/layout/app/Bar.vue')['default']
    LayoutAppDrawer: typeof import('./fragments/layout/app/drawer/Drawer.vue')['default']
    LayoutAppDrawerFooter: typeof import('./fragments/layout/app/drawer/Footer.vue')['default']
    LayoutAppDrawerMenu: typeof import('./fragments/layout/app/drawer/menu/Menu.vue')['default']
    LayoutAppDrawerMenuAccount: typeof import('./fragments/layout/app/drawer/menu/Account.vue')['default']
    LayoutAppDrawerMenuHistory: typeof import('./fragments/layout/app/drawer/menu/History.vue')['default']
    LayoutAppDrawerMenuImport: typeof import('./fragments/layout/app/drawer/menu/Import.vue')['default']
    LayoutAppDrawerMenuLogout: typeof import('./fragments/layout/app/drawer/menu/Logout.vue')['default']
    LayoutAppDrawerMenuMedia: typeof import('./fragments/layout/app/drawer/menu/Media.vue')['default']
    LayoutAppDrawerMenuServer: typeof import('./fragments/layout/app/drawer/menu/Server.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    UserDeletionWarning: typeof import('./components/user/DeletionWarning.vue')['default']
    UserFormChangePassword: typeof import('./components/user/form/ChangePassword.vue')['default']
    UserFormCreateEdit: typeof import('./components/user/form/CreateEdit.vue')['default']
  }
}
