/* eslint-disable */
/* prettier-ignore */
// oxfmt-ignore
// @ts-nocheck
// noinspection ES6UnusedImports
// Generated by vue-router. !! DO NOT MODIFY THIS FILE !!
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

import type {
  RouteRecordInfo,
  ParamValue,
  ParamValueOneOrMore,
  ParamValueZeroOrMore,
  ParamValueZeroOrOne,
} from 'vue-router'
import type {
  _ExtractParamParserType,
} from 'vue-router/experimental'

declare module 'vue-router' {
  interface TypesConfig {
    _ParamParsers: {}
    RouteNamedMap: import('vue-router/auto-routes').RouteNamedMap
    _RouteFileInfoMap: import('vue-router/auto-routes')._RouteFileInfoMap
  }
}

declare module 'vue-router/auto-routes' {
  /**
   * Route name map generated by vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<
      '/',
      '/',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/[...path]': RouteRecordInfo<
      '/[...path]',
      '/:path(.*)',
      { path: ParamValue<true> },
      { path: ParamValue<false> },
      | never
    >,
    '/account/activity': RouteRecordInfo<
      '/account/activity',
      '/account/activity',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/account/api-keys': RouteRecordInfo<
      '/account/api-keys',
      '/account/api-keys',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/account/details': RouteRecordInfo<
      '/account/details',
      '/account/details',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/account/ui': RouteRecordInfo<
      '/account/ui',
      '/account/ui',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/book/[id]': RouteRecordInfo<
      '/book/[id]',
      '/book/:id',
      { id: ParamValue<true> },
      { id: ParamValue<false> },
      | never
    >,
    '/claim': RouteRecordInfo<
      '/claim',
      '/claim',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/collection/[id]': RouteRecordInfo<
      '/collection/[id]',
      '/collection/:id',
      { id: ParamValue<true> },
      { id: ParamValue<false> },
      | never
    >,
    '/error': RouteRecordInfo<
      '/error',
      '/error',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/history': RouteRecordInfo<
      '/history',
      '/history',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/import/books': RouteRecordInfo<
      '/import/books',
      '/import/books',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/import/readlist': RouteRecordInfo<
      '/import/readlist',
      '/import/readlist',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/libraries/[viewId]': RouteRecordInfo<
      '/libraries/[viewId]',
      '/libraries/:viewId',
      { viewId: ParamValue<true> },
      { viewId: ParamValue<false> },
      | '/libraries/[viewId]/books'
      | '/libraries/[viewId]/collections'
      | '/libraries/[viewId]/overview'
      | '/libraries/[viewId]/overview/[section]'
      | '/libraries/[viewId]/readlists'
      | '/libraries/[viewId]/series'
    >,
    '/libraries/[viewId]/books': RouteRecordInfo<
      '/libraries/[viewId]/books',
      '/libraries/:viewId/books',
      { viewId: ParamValue<true> },
      { viewId: ParamValue<false> },
      | never
    >,
    '/libraries/[viewId]/collections': RouteRecordInfo<
      '/libraries/[viewId]/collections',
      '/libraries/:viewId/collections',
      { viewId: ParamValue<true> },
      { viewId: ParamValue<false> },
      | never
    >,
    '/libraries/[viewId]/overview': RouteRecordInfo<
      '/libraries/[viewId]/overview',
      '/libraries/:viewId/overview',
      { viewId: ParamValue<true> },
      { viewId: ParamValue<false> },
      | '/libraries/[viewId]/overview/[section]'
    >,
    '/libraries/[viewId]/overview/[section]': RouteRecordInfo<
      '/libraries/[viewId]/overview/[section]',
      '/libraries/:viewId/overview/:section',
      { viewId: ParamValue<true>, section: ParamValue<true> },
      { viewId: ParamValue<false>, section: ParamValue<false> },
      | never
    >,
    '/libraries/[viewId]/readlists': RouteRecordInfo<
      '/libraries/[viewId]/readlists',
      '/libraries/:viewId/readlists',
      { viewId: ParamValue<true> },
      { viewId: ParamValue<false> },
      | never
    >,
    '/libraries/[viewId]/series': RouteRecordInfo<
      '/libraries/[viewId]/series',
      '/libraries/:viewId/series',
      { viewId: ParamValue<true> },
      { viewId: ParamValue<false> },
      | never
    >,
      '/libraries/create': RouteRecordInfo<
      '/libraries/create',
      '/libraries/create',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/login': RouteRecordInfo<
      '/login',
      '/login',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/media/analysis': RouteRecordInfo<
      '/media/analysis',
      '/media/analysis',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/media/duplicate-files': RouteRecordInfo<
      '/media/duplicate-files',
      '/media/duplicate-files',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/media/duplicate-pages/known': RouteRecordInfo<
      '/media/duplicate-pages/known',
      '/media/duplicate-pages/known',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/media/duplicate-pages/unknown': RouteRecordInfo<
      '/media/duplicate-pages/unknown',
      '/media/duplicate-pages/unknown',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/media/missing-posters': RouteRecordInfo<
      '/media/missing-posters',
      '/media/missing-posters',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/readlist/[id]': RouteRecordInfo<
      '/readlist/[id]',
      '/readlist/:id',
      { id: ParamValue<true> },
      { id: ParamValue<false> },
      | never
    >,
    '/series/[id]': RouteRecordInfo<
      '/series/[id]',
      '/series/:id',
      { id: ParamValue<true> },
      { id: ParamValue<false> },
      | never
    >,
    '/server/activity': RouteRecordInfo<
      '/server/activity',
      '/server/activity',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/server/announcements': RouteRecordInfo<
      '/server/announcements',
      '/server/announcements',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/server/metrics': RouteRecordInfo<
      '/server/metrics',
      '/server/metrics',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/server/settings': RouteRecordInfo<
      '/server/settings',
      '/server/settings',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/server/ui': RouteRecordInfo<
      '/server/ui',
      '/server/ui',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/server/updates': RouteRecordInfo<
      '/server/updates',
      '/server/updates',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/server/users': RouteRecordInfo<
      '/server/users',
      '/server/users',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/startup': RouteRecordInfo<
      '/startup',
      '/startup',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
  }

  /**
   * Route file to route info map by vue-router.
   * Used by the \`sfc-typed-router\` Volar plugin to automatically type \`useRoute()\`.
   *
   * Each key is a file path relative to the project root with 2 properties:
   * - routes: union of route names of the possible routes when in this page (passed to useRoute<...>())
   * - views: names of nested views (can be passed to <RouterView name="...">)
   *
   * @internal
   */
  export interface _RouteFileInfoMap {
    'src/pages/index.vue': {
      routes:
        | '/'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/[...path].vue': {
      routes:
        | '/[...path]'
      views:
        | never
      pathParamNames:
        | 'path'
    }
    'src/pages/account/activity.vue': {
      routes:
        | '/account/activity'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/account/api-keys.vue': {
      routes:
        | '/account/api-keys'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/account/details.vue': {
      routes:
        | '/account/details'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/account/ui.vue': {
      routes:
        | '/account/ui'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/book/[id].vue': {
      routes:
        | '/book/[id]'
      views:
        | never
      pathParamNames:
        | 'id'
    }
    'src/pages/claim.vue': {
      routes:
        | '/claim'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/collection/[id].vue': {
      routes:
        | '/collection/[id]'
      views:
        | never
      pathParamNames:
        | 'id'
    }
    'src/pages/error.vue': {
      routes:
        | '/error'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/history.vue': {
      routes:
        | '/history'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/import/books.vue': {
      routes:
        | '/import/books'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/import/readlist.vue': {
      routes:
        | '/import/readlist'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/libraries/[viewId].vue': {
      routes:
        | '/libraries/[viewId]'
        | '/libraries/[viewId]/books'
        | '/libraries/[viewId]/collections'
        | '/libraries/[viewId]/overview'
        | '/libraries/[viewId]/overview/[section]'
        | '/libraries/[viewId]/readlists'
        | '/libraries/[viewId]/series'
      views:
        | 'default'
      pathParamNames:
        | 'viewId'
    }
    'src/pages/libraries/[viewId]/books.vue': {
      routes:
        | '/libraries/[viewId]/books'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/libraries/[viewId]/collections.vue': {
      routes:
        | '/libraries/[viewId]/collections'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/libraries/[viewId]/overview.vue': {
      routes:
        | '/libraries/[viewId]/overview'
        | '/libraries/[viewId]/overview/[section]'
      views:
        | 'default'
      pathParamNames:
        | never
    }
    'src/pages/libraries/[viewId]/overview/[section].vue': {
      routes:
        | '/libraries/[viewId]/overview/[section]'
      views:
        | never
      pathParamNames:
        | 'section'
    }
    'src/pages/libraries/[viewId]/readlists.vue': {
      routes:
        | '/libraries/[viewId]/readlists'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/libraries/[viewId]/series.vue': {
      routes:
        | '/libraries/[viewId]/series'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/libraries/create.vue': {
      routes:
        | '/libraries/create'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/login.vue': {
      routes:
        | '/login'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/media/analysis.vue': {
      routes:
        | '/media/analysis'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/media/duplicate-files.vue': {
      routes:
        | '/media/duplicate-files'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/media/duplicate-pages/known.vue': {
      routes:
        | '/media/duplicate-pages/known'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/media/duplicate-pages/unknown.vue': {
      routes:
        | '/media/duplicate-pages/unknown'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/media/missing-posters.vue': {
      routes:
        | '/media/missing-posters'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/readlist/[id].vue': {
      routes:
        | '/readlist/[id]'
      views:
        | never
      pathParamNames:
        | 'id'
    }
    'src/pages/series/[id].vue': {
      routes:
        | '/series/[id]'
      views:
        | never
      pathParamNames:
        | 'id'
    }
    'src/pages/server/activity.vue': {
      routes:
        | '/server/activity'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/server/announcements.vue': {
      routes:
        | '/server/announcements'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/server/metrics.vue': {
      routes:
        | '/server/metrics'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/server/settings.vue': {
      routes:
        | '/server/settings'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/server/ui.vue': {
      routes:
        | '/server/ui'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/server/updates.vue': {
      routes:
        | '/server/updates'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/server/users.vue': {
      routes:
        | '/server/users'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/startup.vue': {
      routes:
        | '/startup'
      views:
        | never
      pathParamNames:
        | never
    }
  }

  /**
   * Get a union of possible route names in a certain route component file.
   * Used by the \`sfc-typed-router\` Volar plugin to automatically type \`useRoute()\`.
   *
   * @internal
   */
  export type _RouteNamesForFilePath<FilePath extends string> =
    _RouteFileInfoMap extends Record<FilePath, infer Info>
      ? Info['routes']
      : keyof RouteNamedMap
}

export {}
