/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// noinspection ES6UnusedImports
// Generated by unplugin-vue-router. !! DO NOT MODIFY THIS FILE !!
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-resolver' {
  export type ParamParserCustom = never
}

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<
      '/',
      '/',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/[...path]': RouteRecordInfo<
      '/[...path]',
      '/:path(.*)',
      { path: ParamValue<true> },
      { path: ParamValue<false> },
      | never
    >,
    '/account/activity': RouteRecordInfo<
      '/account/activity',
      '/account/activity',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/account/api-keys': RouteRecordInfo<
      '/account/api-keys',
      '/account/api-keys',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/account/details': RouteRecordInfo<
      '/account/details',
      '/account/details',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/account/ui': RouteRecordInfo<
      '/account/ui',
      '/account/ui',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/claim': RouteRecordInfo<
      '/claim',
      '/claim',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/error': RouteRecordInfo<
      '/error',
      '/error',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/history': RouteRecordInfo<
      '/history',
      '/history',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/import/books': RouteRecordInfo<
      '/import/books',
      '/import/books',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/import/readlist': RouteRecordInfo<
      '/import/readlist',
      '/import/readlist',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/libraries/[id]': RouteRecordInfo<
      '/libraries/[id]',
      '/libraries/:id',
      { id: ParamValue<true> },
      { id: ParamValue<false> },
      | '/libraries/[id]/books'
      | '/libraries/[id]/collections'
      | '/libraries/[id]/readlists'
      | '/libraries/[id]/recommended'
      | '/libraries/[id]/series'
    >,
    '/libraries/[id]/books': RouteRecordInfo<
      '/libraries/[id]/books',
      '/libraries/:id/books',
      { id: ParamValue<true> },
      { id: ParamValue<false> },
      | never
    >,
    '/libraries/[id]/collections': RouteRecordInfo<
      '/libraries/[id]/collections',
      '/libraries/:id/collections',
      { id: ParamValue<true> },
      { id: ParamValue<false> },
      | never
    >,
    '/libraries/[id]/readlists': RouteRecordInfo<
      '/libraries/[id]/readlists',
      '/libraries/:id/readlists',
      { id: ParamValue<true> },
      { id: ParamValue<false> },
      | never
    >,
    '/libraries/[id]/recommended': RouteRecordInfo<
      '/libraries/[id]/recommended',
      '/libraries/:id/recommended',
      { id: ParamValue<true> },
      { id: ParamValue<false> },
      | never
    >,
    '/libraries/[id]/series': RouteRecordInfo<
      '/libraries/[id]/series',
      '/libraries/:id/series',
      { id: ParamValue<true> },
      { id: ParamValue<false> },
      | never
    >,
    '/login': RouteRecordInfo<
      '/login',
      '/login',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/media/analysis': RouteRecordInfo<
      '/media/analysis',
      '/media/analysis',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/media/duplicate-files': RouteRecordInfo<
      '/media/duplicate-files',
      '/media/duplicate-files',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/media/duplicate-pages/known': RouteRecordInfo<
      '/media/duplicate-pages/known',
      '/media/duplicate-pages/known',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/media/duplicate-pages/unknown': RouteRecordInfo<
      '/media/duplicate-pages/unknown',
      '/media/duplicate-pages/unknown',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/media/missing-posters': RouteRecordInfo<
      '/media/missing-posters',
      '/media/missing-posters',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/server/activity': RouteRecordInfo<
      '/server/activity',
      '/server/activity',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/server/announcements': RouteRecordInfo<
      '/server/announcements',
      '/server/announcements',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/server/metrics': RouteRecordInfo<
      '/server/metrics',
      '/server/metrics',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/server/settings': RouteRecordInfo<
      '/server/settings',
      '/server/settings',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/server/ui': RouteRecordInfo<
      '/server/ui',
      '/server/ui',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/server/updates': RouteRecordInfo<
      '/server/updates',
      '/server/updates',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/server/users': RouteRecordInfo<
      '/server/users',
      '/server/users',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/startup': RouteRecordInfo<
      '/startup',
      '/startup',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
  }

  /**
   * Route file to route info map by unplugin-vue-router.
   * Used by the \`sfc-typed-router\` Volar plugin to automatically type \`useRoute()\`.
   *
   * Each key is a file path relative to the project root with 2 properties:
   * - routes: union of route names of the possible routes when in this page (passed to useRoute<...>())
   * - views: names of nested views (can be passed to <RouterView name="...">)
   *
   * @internal
   */
  export interface _RouteFileInfoMap {
    'src/pages/index.vue': {
      routes:
        | '/'
      views:
        | never
    }
    'src/pages/[...path].vue': {
      routes:
        | '/[...path]'
      views:
        | never
    }
    'src/pages/account/activity.vue': {
      routes:
        | '/account/activity'
      views:
        | never
    }
    'src/pages/account/api-keys.vue': {
      routes:
        | '/account/api-keys'
      views:
        | never
    }
    'src/pages/account/details.vue': {
      routes:
        | '/account/details'
      views:
        | never
    }
    'src/pages/account/ui.vue': {
      routes:
        | '/account/ui'
      views:
        | never
    }
    'src/pages/claim.vue': {
      routes:
        | '/claim'
      views:
        | never
    }
    'src/pages/error.vue': {
      routes:
        | '/error'
      views:
        | never
    }
    'src/pages/history.vue': {
      routes:
        | '/history'
      views:
        | never
    }
    'src/pages/import/books.vue': {
      routes:
        | '/import/books'
      views:
        | never
    }
    'src/pages/import/readlist.vue': {
      routes:
        | '/import/readlist'
      views:
        | never
    }
    'src/pages/libraries/[id].vue': {
      routes:
        | '/libraries/[id]'
        | '/libraries/[id]/books'
        | '/libraries/[id]/collections'
        | '/libraries/[id]/readlists'
        | '/libraries/[id]/recommended'
        | '/libraries/[id]/series'
      views:
        | 'default'
    }
    'src/pages/libraries/[id]/books.vue': {
      routes:
        | '/libraries/[id]/books'
      views:
        | never
    }
    'src/pages/libraries/[id]/collections.vue': {
      routes:
        | '/libraries/[id]/collections'
      views:
        | never
    }
    'src/pages/libraries/[id]/readlists.vue': {
      routes:
        | '/libraries/[id]/readlists'
      views:
        | never
    }
    'src/pages/libraries/[id]/recommended.vue': {
      routes:
        | '/libraries/[id]/recommended'
      views:
        | never
    }
    'src/pages/libraries/[id]/series.vue': {
      routes:
        | '/libraries/[id]/series'
      views:
        | never
    }
    'src/pages/login.vue': {
      routes:
        | '/login'
      views:
        | never
    }
    'src/pages/media/analysis.vue': {
      routes:
        | '/media/analysis'
      views:
        | never
    }
    'src/pages/media/duplicate-files.vue': {
      routes:
        | '/media/duplicate-files'
      views:
        | never
    }
    'src/pages/media/duplicate-pages/known.vue': {
      routes:
        | '/media/duplicate-pages/known'
      views:
        | never
    }
    'src/pages/media/duplicate-pages/unknown.vue': {
      routes:
        | '/media/duplicate-pages/unknown'
      views:
        | never
    }
    'src/pages/media/missing-posters.vue': {
      routes:
        | '/media/missing-posters'
      views:
        | never
    }
    'src/pages/server/activity.vue': {
      routes:
        | '/server/activity'
      views:
        | never
    }
    'src/pages/server/announcements.vue': {
      routes:
        | '/server/announcements'
      views:
        | never
    }
    'src/pages/server/metrics.vue': {
      routes:
        | '/server/metrics'
      views:
        | never
    }
    'src/pages/server/settings.vue': {
      routes:
        | '/server/settings'
      views:
        | never
    }
    'src/pages/server/ui.vue': {
      routes:
        | '/server/ui'
      views:
        | never
    }
    'src/pages/server/updates.vue': {
      routes:
        | '/server/updates'
      views:
        | never
    }
    'src/pages/server/users.vue': {
      routes:
        | '/server/users'
      views:
        | never
    }
    'src/pages/startup.vue': {
      routes:
        | '/startup'
      views:
        | never
    }
  }

  /**
   * Get a union of possible route names in a certain route component file.
   * Used by the \`sfc-typed-router\` Volar plugin to automatically type \`useRoute()\`.
   *
   * @internal
   */
  export type _RouteNamesForFilePath<FilePath extends string> =
    _RouteFileInfoMap extends Record<FilePath, infer Info>
      ? Info['routes']
      : keyof RouteNamedMap
}
