CREATE TABLE THUMBNAIL_SERIES
(
    ID                 varchar  NOT NULL PRIMARY KEY,
    URL                varchar  NOT NULL,
    SELECTED           boolean  NOT NULL DEFAULT false,
    CREATED_DATE       timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    LAST_MODIFIED_DATE timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    SERIES_ID          varchar  NOT NULL,
    FOREIGN KEY (SERIES_ID) REFERENCES SERIES (ID)
);
