/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// noinspection JSUnusedGlobalSymbols
// Auto generated by vite-plugin-dir2json
declare module "*i18n?dir2json&ext=.json&lazy" {
  const json: {};
  export default json;
}

declare module "*dir2json" {
  const json: any;
  export default json;
}