import { defineConfig } from '@hey-api/openapi-ts'
import * as fs from 'node:fs'

// 1. Load the spec manually
const specRaw = fs.readFileSync('../komga/docs/openapi.json', 'utf-8')
const spec = JSON.parse(specRaw)

// 2. Strip out the path-level strings that crash the MSW plugin
for (const pathKey in spec.paths) {
  const pathItem = spec.paths[pathKey]
  delete pathItem.summary
  delete pathItem.description
}

export default defineConfig({
  input: spec,
  output: {
    path: './src/generated/openapi',
    header: [
      '/* eslint-disable */',
      '// @ts-nocheck',
      '// This file is auto-generated by @hey-api/openapi-ts',
    ],
  },
  parser: {
    filters: {
      deprecated: false, // don't include deprecated APIs
    },
    transforms: {
      enums: 'root',
    },
  },
  plugins: [
    {
      name: '@hey-api/client-fetch',
    },
    {
      name: '@hey-api/typescript',
      enums: false,
    },
    {
      name: '@hey-api/sdk',
      responseStyle: 'data',
      operations: {
        strategy: 'flat',
        methodName: (operation: string) => {
          const originalName = operation
          if (!originalName) return 'unnamedOperation'

          const capitalizedName = originalName.charAt(0).toUpperCase() + originalName.slice(1)
          return `komga${capitalizedName}`
        },
      },
    },
    {
      name: '@hey-api/transformers',
      dates: true,
      bigInt: false,
    },
    {
      name: 'msw',
    },
  ],
})
