/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppBar: typeof import('./components/app/Bar.vue')['default']
    AppDrawer: typeof import('./components/app/drawer/Drawer.vue')['default']
    AppDrawerFooter: typeof import('./components/app/drawer/Footer.vue')['default']
    AppDrawerMenu: typeof import('./components/app/drawer/menu/Menu.vue')['default']
    AppDrawerMenuAccount: typeof import('./components/app/drawer/menu/Account.vue')['default']
    AppDrawerMenuHistory: typeof import('./components/app/drawer/menu/History.vue')['default']
    AppDrawerMenuImport: typeof import('./components/app/drawer/menu/Import.vue')['default']
    AppDrawerMenuLogout: typeof import('./components/app/drawer/menu/Logout.vue')['default']
    AppDrawerMenuMedia: typeof import('./components/app/drawer/menu/Media.vue')['default']
    AppDrawerMenuServer: typeof import('./components/app/drawer/menu/Server.vue')['default']
    EssentialLink: typeof import('./components/EssentialLink.vue')['default']
    ExampleComponent: typeof import('./components/ExampleComponent.vue')['default']
    FormUserChangePassword: typeof import('./components/form/user/ChangePassword.vue')['default']
    FormUserEdit: typeof import('./components/form/user/Edit.vue')['default']
    KBanner: typeof import('./components/KBanner.vue')['default']
    KEmptyState: typeof import('./components/KEmptyState.vue')['default']
    QTable: typeof import('quasar')['QTable']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    ThemeSelector: typeof import('./components/ThemeSelector.vue')['default']
  }
}
