/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppBar: typeof import('./components/app/Bar.vue')['default']
    AppDrawer: typeof import('./components/app/drawer/Drawer.vue')['default']
    AppDrawerFooter: typeof import('./components/app/drawer/Footer.vue')['default']
    AppDrawerMenu: typeof import('./components/app/drawer/menu/Menu.vue')['default']
    AppDrawerMenuAccount: typeof import('./components/app/drawer/menu/Account.vue')['default']
    AppDrawerMenuHistory: typeof import('./components/app/drawer/menu/History.vue')['default']
    AppDrawerMenuImport: typeof import('./components/app/drawer/menu/Import.vue')['default']
    AppDrawerMenuLogout: typeof import('./components/app/drawer/menu/Logout.vue')['default']
    AppDrawerMenuMedia: typeof import('./components/app/drawer/menu/Media.vue')['default']
    AppDrawerMenuMenu: typeof import('./components/app/drawer/menu/Menu.vue')['default']
    AppDrawerMenuServer: typeof import('./components/app/drawer/menu/Server.vue')['default']
    EmptyState: typeof import('./components/EmptyState.vue')['default']
    EssentialLink: typeof import('./components/EssentialLink.vue')['default']
    ExampleComponent: typeof import('./components/ExampleComponent.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
