CREATE TABLE SERVER_SETTINGS
(
    KEY   varchar NOT NULL PRIMARY KEY,
    VALUE varchar NULL
);

INSERT INTO SERVER_SETTINGS
VALUES ('DELETE_EMPTY_COLLECTIONS', ${delete-empty-collections});
INSERT INTO SERVER_SETTINGS
VALUES ('DELETE_EMPTY_READLISTS', ${delete-empty-read-lists});
INSERT INTO SERVER_SETTINGS
VALUES ('REMEMBER_ME_KEY', hex(randomblob(32)));
INSERT INTO SERVER_SETTINGS
VALUES ('REMEMBER_ME_DURATION', 365);
