CREATE TABLE SERIES_METADATA_ALTERNATIVE_TITLE
(
    TITLE     varchar NOT NULL,
    HINT      varchar,
    SERIES_ID varchar NOT NULL,
    FOREIGN KEY (SERIES_ID) REFERENCES SERIES (ID)
);
alter table SERIES_METADATA
    add column ALTERNATIVE_TITLES_LOCK boolean NOT NULL DEFAULT 0;

CREATE INDEX idx__series_metadata_alternative_title__series_id on SERIES_METADATA_ALTERNATIVE_TITLE (SERIES_ID);
