ALTER TABLE BOOK
    ADD COLUMN FILE_HASH varchar NOT NULL DEFAULT '';
ALTER TABLE BOOK
    ADD COLUMN DELETED boolean NOT NULL DEFAULT 0;
ALTER TABLE SERIES
    ADD COLUMN DELETED boolean NOT NULL DEFAULT 0;
