CREATE TABLE BOOK_PROJECTION
(
    BOOK_ID            varchar  NOT NULL,
    PROFILE            varchar  NOT NULL,
    FILE_SIZE          int8     NOT NULL,
    CREATED_DATE       datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
    LAST_MODIFIED_DATE datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (BOOK_ID, PROFILE),
    FOREIGN KEY (BOOK_ID) REFERENCES BOOK (ID)
);
