CREATE TABLE SERIES_METADATA_SHARING
(
    LABEL     varchar NOT NULL,
    SERIES_ID varchar NOT NULL,
    FOREIGN KEY (SERIES_ID) REFERENCES SERIES (ID)
);

alter table SERIES_METADATA
    add column SHARING_LABELS_LOCK boolean NOT NULL DEFAULT 0;
