ALTER TABLE BOOK
    ADD COLUMN FILE_HASH varchar NOT NULL DEFAULT '';

ALTER TABLE BOOK
    ADD COLUMN DELETED_DATE datetime NULL DEFAULT NULL;

ALTER TABLE SERIES
    ADD COLUMN DELETED_DATE datetime NULL DEFAULT NULL;
