komga:
  workspace: localdb
  database:
    file: \${komga.config-dir}/\${komga.workspace}.sqlite
  lucene:
    data-directory: \${komga.config-dir}/lucene/\${komga.workspace}
  tasks-db:
    file: \${komga.config-dir}/\${komga.workspace}-tasks.sqlite
spring:
  artemis:
    embedded:
      data-directory: \${komga.config-dir}/artemis/\${komga.workspace}
