export enum SeriesCoverDto {
  FIRST = 'FIRST',
  FIRST_UNREAD_OR_FIRST = 'FIRST_UNREAD_OR_FIRST',
  FIRST_UNREAD_OR_LAST = 'FIRST_UNREAD_OR_LAST',
  LAST = 'LAST',
}

export enum SeriesSortDto {
  NAME_NATURAL = 'NAME_NATURAL',
  FILE_MODIFIED_ASC = 'FILE_MODIFIED_ASC',
  FILE_MODIFIED_DESC = 'FILE_MODIFIED_DESC', 
}

export enum ScanIntervalDto {
  DISABLED = 'DISABLED',
  HOURLY = 'HOURLY',
  EVERY_6H = 'EVERY_6H',
  EVERY_12H = 'EVERY_12H',
  DAILY = 'DAILY',
  WEEKLY = 'WEEKLY',
}
