name: Test WebUI

on:
  pull_request:
    paths:
      - 'komga-webui/**'
      - '!komga-webui/src/locales/*'
  push:
    paths:
      - '.github/workflows/test-webui.yml'
      - 'komga-webui/**'
      - '!komga-webui/src/locales/*'
    branches-ignore:
      - 'dependabot/**'
  workflow_dispatch:

permissions:
  contents: read

jobs:
  webui:
    runs-on: ubuntu-latest
    name: Test webui
    steps:
      - uses: actions/checkout@v7

      - name: WebUI - Setup
        uses: ./.github/actions/setup-web
        with:
          working-directory: komga-webui

      - name: npm build
        working-directory: komga-webui
        run: npm run build
        env:
          NODE_OPTIONS: "--max-old-space-size=4096"

      - name: npm test
        working-directory: komga-webui
        run: npm run test:unit
