name: Test NextUI

on:
  pull_request:
    paths:
      - 'next-ui/**'
      - '!next-ui/i18n/*'
  push:
    paths:
      - '.github/workflows/test-nextui.yml'
      - 'next-ui/**'
      - '!next-ui/i18n/*'
    branches-ignore:
      - 'dependabot/**'
  workflow_dispatch:

jobs:
  test-unit:
    runs-on: ubuntu-latest
    name: Test unit
    steps:
      - uses: actions/checkout@v6
      - name: NextUI - Setup
        uses: ./.github/actions/setup-web
        with:
          working-directory: next-ui
      - name: test:unit
        working-directory: next-ui
        run: npm run test:unit

  test-storybook:
    runs-on: ubuntu-latest
    name: Test storybook
    steps:
      - uses: actions/checkout@v6
      - name: NextUI - Setup
        uses: ./.github/actions/setup-web
        with:
          working-directory: next-ui
      - name: Setup Playwright
        uses: ./.github/actions/setup-playwright
        with:
          working-directory: next-ui
      - name: test:storybook
        working-directory: next-ui
        run: npm run test:storybook
        env:
          LANG: en_US

  lint:
    runs-on: ubuntu-latest
    name: Lint
    steps:
      - uses: actions/checkout@v6
      - name: NextUI - Setup
        uses: ./.github/actions/setup-web
        with:
          working-directory: next-ui
      - name: lint
        working-directory: next-ui
        run: npm run lint

  prettier:
    runs-on: ubuntu-latest
    name: Prettier
    steps:
      - uses: actions/checkout@v6
      - name: NextUI - Setup
        uses: ./.github/actions/setup-web
        with:
          working-directory: next-ui
      - name: prettier
        working-directory: next-ui
        run: npm run prettier

  type-check:
    runs-on: ubuntu-latest
    name: Type check
    steps:
      - uses: actions/checkout@v6
      - name: NextUI - Setup
        uses: ./.github/actions/setup-web
        with:
          working-directory: next-ui
      - name: type-check
        working-directory: next-ui
        run: npm run type-check

  build:
    runs-on: ubuntu-latest
    name: Build
    steps:
      - uses: actions/checkout@v6
      - name: NextUI - Setup
        uses: ./.github/actions/setup-web
        with:
          working-directory: next-ui
      - name: build
        working-directory: next-ui
        run: npm run build

  check-i18n:
    runs-on: ubuntu-latest
    name: Check for missing i18n
    steps:
      - uses: actions/checkout@v6
      - name: NextUI - Setup
        uses: ./.github/actions/setup-web
        with:
          working-directory: next-ui
      - name: check for missing i18n extract
        working-directory: next-ui
        run: |
          npm run i18n:extract
          git diff --exit-code
